algoritmo "semnome"
// Função :
// Autor :
// Data : 07/03/2017
// Seção de Declarações 
var

n1 , n2 , n3 , n4 : inteiro
mult , soma : real

inicio
// Seção de Comandos 


escreval("Digite um Numero")
leia(n1)

escreval("Digite um Numero")
leia(n2)

escreval("Digite um Numero")
leia(n3)

escreval("Digite um Numero")
leia(n4)

mult <- n1 * n3
soma <- n2 + n4

escreval("Resultado",mult)
escreval("soma",soma)

fimalgoritmo
